org.springframework.dao.TransientDataAccessResourceException: Error attempting to get column 'exp_date' from result set.  Cause: java.sql.SQLException: Value '0000-00-00' can not be represented as java.sql.Date